In [2]:
import numpy as np
n1=np.array([10,20,30,40])
n1

array([10, 20, 30, 40])

In [3]:
import numpy as np
n2=np.array([[10,20,30,40],[40,30,20,10]])
n2


array([[10, 20, 30, 40],
       [40, 30, 20, 10]])

In [5]:
import numpy as np
n1=np.zeros((1,2))
n1

array([[0., 0.]])

In [6]:
import numpy as np
n2=np.zeros((5,5))
n2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
import numpy as np
n1=np.full((2,2),10)
n1

array([[10, 10],
       [10, 10]])

In [8]:
import numpy as np
n1=np.arange(10,20)
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [9]:
import numpy as np
n1=np.arange(10,50,5)
n1

array([10, 15, 20, 25, 30, 35, 40, 45])

In [21]:
import numpy as np
n1=np.random.randint(1,100,5)
n1

array([ 1, 76, 42, 38, 81], dtype=int32)

In [23]:
import numpy as np
n1=np.array([[1, 2, 3],[4, 5, 6]])
n1.shape

(2, 3)

In [24]:
import numpy as np
n1=np.array([10,20,30])
n2=np.array([40,50,60])
np.vstack((n1,n2))

array([[10, 20, 30],
       [40, 50, 60]])

In [25]:
import numpy as np
n1=np.array([10,20,30])
n2=np.array([40,50,60])
np.hstack((n1,n2))

array([10, 20, 30, 40, 50, 60])

In [3]:
import numpy as np
n1=np.array([10,20,30])
n2=np.array([40,50,60])
np.column_stack((n1,n2))

array([[10, 40],
       [20, 50],
       [30, 60]])

In [4]:
n1=np.array([[1,2,3],[4,5,6],[7,8,9]])
n1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
n2=np.array([[9,8,7],[6,5,4],[3,2,1]])
n2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [6]:
n1.dot(n2)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [7]:
n2.dot(n1)

array([[ 90, 114, 138],
       [ 54,  69,  84],
       [ 18,  24,  30]])